//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharedLibrary.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenisini yarat.
        /// </summary>
        internal static string action_create {
            get {
                return ResourceManager.GetString("action_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string action_delete {
            get {
                return ResourceManager.GetString("action_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel endir.
        /// </summary>
        internal static string action_exportFile {
            get {
                return ResourceManager.GetString("action_exportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reyestr.
        /// </summary>
        internal static string action_getAll {
            get {
                return ResourceManager.GetString("action_getAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detallara bax.
        /// </summary>
        internal static string action_getById {
            get {
                return ResourceManager.GetString("action_getById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenilə.
        /// </summary>
        internal static string action_update {
            get {
                return ResourceManager.GetString("action_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fayl yüklə.
        /// </summary>
        internal static string action_uploadFile {
            get {
                return ResourceManager.GetString("action_uploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bildirişlər.
        /// </summary>
        internal static string page_notification {
            get {
                return ResourceManager.GetString("page_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hüquqlar.
        /// </summary>
        internal static string page_permission {
            get {
                return ResourceManager.GetString("page_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büdcə hesabatı.
        /// </summary>
        internal static string page_report {
            get {
                return ResourceManager.GetString("page_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstifadəçi.
        /// </summary>
        internal static string page_user {
            get {
                return ResourceManager.GetString("page_user", resourceCulture);
            }
        }
    }
}
